FROM python:3.10-slim

WORKDIR /app

# system deps for opencv and insightface (keep minimal)
RUN apt-get update && apt-get install -y \
    build-essential \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender-dev \
    ffmpeg \
    wget \
&& rm -rf /var/lib/apt/lists/*

# Copy requirements and install
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# copy app
COPY . /app

EXPOSE 8000

# default command (overidden in docker-compose for reload)
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]